services:
  nextjs:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - nextjs-data:/app/.next 
  go:
    container_name: go
    build: 
      context: ./backend/go
      dockerfile: go.dockerfile
    ports:
      - "8080:8080" 
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  nextjs-data:
  postgres-data: