version: "3.8"

services:
  nextjs:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - nextjs-data:/app/.next 
    depends_on:
      - go
  go:
    container_name: go
    build: 
      context: ./backend/go
      dockerfile: go.dockerfile
    ports:
      - "8080:8080" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: go
    depends_on:
      - db 
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  nextjs-data:
  db-data: