version: '3.8'

services:
  # Frontend development overrides
  frontend:
    build:
      context: ./frontend
      target: builder
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - BACKEND_URL=http://backend:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - social-media-network

  # Backend development overrides
  backend:
    build:
      context: ./backend/go
      target: development
    command: go run cmd/v1/session/main.go
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
    volumes:
      - ./backend/go:/app
    networks:
      - social-media-network