---
# Elasticsearch Index Lifecycle Management
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-ilm-policy
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch-ilm
data:
  ilm-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_size": "5GB",
                "max_age": "1d"
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "7d",
            "actions": {
              "set_priority": {
                "priority": 50
              },
              "allocate": {
                "number_of_replicas": 1
              },
              "shrink": {
                "number_of_shards": 1
              }
            }
          },
          "cold": {
            "min_age": "30d",
            "actions": {
              "set_priority": {
                "priority": 0
              },
              "allocate": {
                "number_of_replicas": 0
              }
            }
          },
          "delete": {
            "min_age": "90d"
          }
        }
      }
    }
  
  index-template.json: |
    {
      "index_patterns": ["social-media-backend-*"],
      "template": {
        "settings": {
          "number_of_shards": 2,
          "number_of_replicas": 1,
          "index.lifecycle.name": "social-media-logs-policy",
          "index.lifecycle.rollover_alias": "social-media-backend",
          "index.refresh_interval": "30s",
          "index.mapping.total_fields.limit": 2000,
          "index.mapping.depth.limit": 20
        },
        "mappings": {
          "properties": {
            "@timestamp": {
              "type": "date"
            },
            "level": {
              "type": "keyword"
            },
            "message": {
              "type": "text",
              "analyzer": "standard"
            },
            "component": {
              "type": "keyword"
            },
            "service": {
              "type": "keyword"
            },
            "environment": {
              "type": "keyword"
            },
            "application": {
              "type": "keyword"
            },
            "version": {
              "type": "keyword"
            },
            "node_name": {
              "type": "keyword"
            },
            "pod_name": {
              "type": "keyword"
            },
            "namespace": {
              "type": "keyword"
            },
            "request_id": {
              "type": "keyword"
            },
            "user_id": {
              "type": "keyword"
            },
            "room_id": {
              "type": "keyword"
            },
            "websocket_event": {
              "type": "keyword"
            },
            "duration_ms": {
              "type": "long"
            },
            "error": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "text"
                },
                "stack": {
                  "type": "text"
                },
                "code": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
---
# CronJob for Elasticsearch maintenance
apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-maintenance
  namespace: logging
  labels:
    app.kubernetes.io/name: elasticsearch-maintenance
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curator
            image: bitnami/elasticsearch-curator:5.8.4
            env:
            - name: ELASTICSEARCH_HOST
              value: "elasticsearch"
            - name: ELASTICSEARCH_PORT
              value: "9200"
            command:
            - /bin/sh
            - -c
            - |
              # Apply ILM policy
              curl -X PUT "elasticsearch:9200/_ilm/policy/social-media-logs-policy" \
                -H 'Content-Type: application/json' \
                -d @/config/ilm-policy.json
              
              # Apply index template
              curl -X PUT "elasticsearch:9200/_index_template/social-media-backend-template" \
                -H 'Content-Type: application/json' \
                -d @/config/index-template.json
              
              # Force merge old indices
              curator --config /config/curator.yml /config/actions.yml
            volumeMounts:
            - name: config
              mountPath: /config
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
          volumes:
          - name: config
            configMap:
              name: elasticsearch-ilm-policy
          restartPolicy: OnFailure
---
# Log Retention ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-retention-config
  namespace: logging
  labels:
    app.kubernetes.io/name: log-retention
data:
  curator.yml: |
    client:
      hosts:
        - elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']
  
  actions.yml: |
    actions:
      1:
        action: delete_indices
        description: "Delete indices older than 90 days"
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: social-media-backend-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 90
          exclude:
      2:
        action: forcemerge
        description: "Force merge indices older than 7 days"
        options:
          max_num_segments: 1
          delay: 120
          timeout_override: 21600
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: social-media-backend-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 7
          exclude:
