openapi: 3.1.0
info:
  title: Real-time Signaling Service API
  description: |-
    This API provides WebSocket endpoints for real-time communication features, including video calls, screen sharing, and text chat.

    **Authentication is required for all endpoints.** A valid JWT must be provided as a `token` query parameter with each connection request.
  version: "1.0.0"
servers:
  - url: "ws://localhost:8080"
    description: Local development server

tags:
  - name: WebSockets
    description: Endpoints for establishing real-time WebSocket connections.

paths:
  /ws/zoom/{roomId}:
    get:
      tags:
        - WebSockets
      summary: Establish a WebSocket connection for a video call.
      description: |-
        Upgrades the HTTP connection to a WebSocket to join a video call room.
        Authentication via a `token` query parameter is required.
        Clients can send/receive WebRTC signaling messages once connected.
      parameters:
        - name: roomId
          in: path
          description: The unique identifier for the video call room to join.
          required: true
          schema:
            type: string
            example: "meeting-12345"
      security:
        - bearerAuth: []
      responses:
        '101':
          description: Switching protocols to WebSocket, indicating a successful connection.
        '401':
          description: Unauthorized. The `token` query parameter is missing, invalid, or expired.
        '403':
          description: Forbidden. The request's `Origin` header is not in the list of allowed origins.

  /ws/screenshare/{roomId}:
    get:
      tags:
        - WebSockets
      summary: Establish a WebSocket connection for screen sharing.
      description: |-
        Upgrades the HTTP connection to a WebSocket to join a screen share session.
        Authentication via a `token` query parameter is required.
      parameters:
        - name: roomId
          in: path
          description: The unique identifier for the screen sharing room to join.
          required: true
          schema:
            type: string
            example: "share-session-abc"
      security:
        - bearerAuth: []
      responses:
        '101':
          description: Switching protocols to WebSocket.
        '401':
          description: Unauthorized. The `token` query parameter is missing, invalid, or expired.
        '403':
          description: Forbidden. The request's `Origin` header is not in the list of allowed origins.

  /ws/chat/{roomId}:
    get:
      tags:
        - WebSockets
      summary: Establish a WebSocket connection for text chat.
      description: |-
        Upgrades the HTTP connection to a WebSocket to join a text chat room.
        Authentication via a `token` query parameter is required.
      parameters:
        - name: roomId
          in: path
          description: The unique identifier for the chat room to join.
          required: true
          schema:
            type: string
            example: "general-chat"
      security:
        - bearerAuth: []
      responses:
        '101':
          description: Switching protocols to WebSocket.
        '401':
          description: Unauthorized. The `token` query parameter is missing, invalid, or expired.
        '403':
          description: Forbidden. The request's `Origin` header is not in the list of allowed origins.

components:
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: query
      name: token
      description: "JWT token obtained from the authentication provider (e.g., Auth0) used to authenticate the WebSocket connection request."